# Generated by Django 4.2 on 2023-04-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_rating_author_authorating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Authorating',
            new_name='ratingAuthor',
        ),
    ]
