# Generated by Django 4.2 on 2023-04-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_authorating_author_ratingauthor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reting',
            new_name='rating',
        ),
    ]
